package com.wangguangwu.mapper;

import com.wangguangwu.entity.Company;
import com.wangguangwu.entity.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author wangguangwu
 */
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int insert(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int insertSelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int updateByExampleSelective(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int updateByExample(@Param("row") Company row, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int updateByPrimaryKeySelective(Company row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    int updateByPrimaryKey(Company row);
}