package com.wangguangwu.entity;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_address
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_industry
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private String companyIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_status
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private String companyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_size
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    private String companySize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param companyName the value for company.company_name
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_address
     *
     * @return the value of company.company_address
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_address
     *
     * @param companyAddress the value for company.company_address
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_industry
     *
     * @return the value of company.company_industry
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public String getCompanyIndustry() {
        return companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_industry
     *
     * @param companyIndustry the value for company.company_industry
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setCompanyIndustry(String companyIndustry) {
        this.companyIndustry = companyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_status
     *
     * @return the value of company.company_status
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public String getCompanyStatus() {
        return companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_status
     *
     * @param companyStatus the value for company.company_status
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setCompanyStatus(String companyStatus) {
        this.companyStatus = companyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_size
     *
     * @return the value of company.company_size
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public String getCompanySize() {
        return companySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_size
     *
     * @param companySize the value for company.company_size
     *
     * @mbg.generated Sat Mar 12 23:05:14 CST 2022
     */
    public void setCompanySize(String companySize) {
        this.companySize = companySize;
    }
}