package com.wangguangwu.entity;

public class Job {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_salary
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_education_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobEducationRequire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_skill_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobSkillRequire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_info_desc
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobInfoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_company
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    private String jobCompany;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_salary
     *
     * @return the value of job.job_salary
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobSalary() {
        return jobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_salary
     *
     * @param jobSalary the value for job.job_salary
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobSalary(String jobSalary) {
        this.jobSalary = jobSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_education_require
     *
     * @return the value of job.job_education_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobEducationRequire() {
        return jobEducationRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_education_require
     *
     * @param jobEducationRequire the value for job.job_education_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobEducationRequire(String jobEducationRequire) {
        this.jobEducationRequire = jobEducationRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_skill_require
     *
     * @return the value of job.job_skill_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobSkillRequire() {
        return jobSkillRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_skill_require
     *
     * @param jobSkillRequire the value for job.job_skill_require
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobSkillRequire(String jobSkillRequire) {
        this.jobSkillRequire = jobSkillRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_info_desc
     *
     * @return the value of job.job_info_desc
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobInfoDesc() {
        return jobInfoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_info_desc
     *
     * @param jobInfoDesc the value for job.job_info_desc
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobInfoDesc(String jobInfoDesc) {
        this.jobInfoDesc = jobInfoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_company
     *
     * @return the value of job.job_company
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getJobCompany() {
        return jobCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_company
     *
     * @param jobCompany the value for job.job_company
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setJobCompany(String jobCompany) {
        this.jobCompany = jobCompany;
    }
}