package com.wangguangwu.entity;

import java.util.ArrayList;
import java.util.List;

public class JobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public JobExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNull() {
            addCriterion("job_salary is null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIsNotNull() {
            addCriterion("job_salary is not null");
            return (Criteria) this;
        }

        public Criteria andJobSalaryEqualTo(String value) {
            addCriterion("job_salary =", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotEqualTo(String value) {
            addCriterion("job_salary <>", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThan(String value) {
            addCriterion("job_salary >", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryGreaterThanOrEqualTo(String value) {
            addCriterion("job_salary >=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThan(String value) {
            addCriterion("job_salary <", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLessThanOrEqualTo(String value) {
            addCriterion("job_salary <=", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryLike(String value) {
            addCriterion("job_salary like", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotLike(String value) {
            addCriterion("job_salary not like", value, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryIn(List<String> values) {
            addCriterion("job_salary in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotIn(List<String> values) {
            addCriterion("job_salary not in", values, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryBetween(String value1, String value2) {
            addCriterion("job_salary between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobSalaryNotBetween(String value1, String value2) {
            addCriterion("job_salary not between", value1, value2, "jobSalary");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireIsNull() {
            addCriterion("job_education_require is null");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireIsNotNull() {
            addCriterion("job_education_require is not null");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireEqualTo(String value) {
            addCriterion("job_education_require =", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireNotEqualTo(String value) {
            addCriterion("job_education_require <>", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireGreaterThan(String value) {
            addCriterion("job_education_require >", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireGreaterThanOrEqualTo(String value) {
            addCriterion("job_education_require >=", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireLessThan(String value) {
            addCriterion("job_education_require <", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireLessThanOrEqualTo(String value) {
            addCriterion("job_education_require <=", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireLike(String value) {
            addCriterion("job_education_require like", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireNotLike(String value) {
            addCriterion("job_education_require not like", value, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireIn(List<String> values) {
            addCriterion("job_education_require in", values, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireNotIn(List<String> values) {
            addCriterion("job_education_require not in", values, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireBetween(String value1, String value2) {
            addCriterion("job_education_require between", value1, value2, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobEducationRequireNotBetween(String value1, String value2) {
            addCriterion("job_education_require not between", value1, value2, "jobEducationRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireIsNull() {
            addCriterion("job_skill_require is null");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireIsNotNull() {
            addCriterion("job_skill_require is not null");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireEqualTo(String value) {
            addCriterion("job_skill_require =", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireNotEqualTo(String value) {
            addCriterion("job_skill_require <>", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireGreaterThan(String value) {
            addCriterion("job_skill_require >", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireGreaterThanOrEqualTo(String value) {
            addCriterion("job_skill_require >=", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireLessThan(String value) {
            addCriterion("job_skill_require <", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireLessThanOrEqualTo(String value) {
            addCriterion("job_skill_require <=", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireLike(String value) {
            addCriterion("job_skill_require like", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireNotLike(String value) {
            addCriterion("job_skill_require not like", value, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireIn(List<String> values) {
            addCriterion("job_skill_require in", values, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireNotIn(List<String> values) {
            addCriterion("job_skill_require not in", values, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireBetween(String value1, String value2) {
            addCriterion("job_skill_require between", value1, value2, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobSkillRequireNotBetween(String value1, String value2) {
            addCriterion("job_skill_require not between", value1, value2, "jobSkillRequire");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescIsNull() {
            addCriterion("job_info_desc is null");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescIsNotNull() {
            addCriterion("job_info_desc is not null");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescEqualTo(String value) {
            addCriterion("job_info_desc =", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescNotEqualTo(String value) {
            addCriterion("job_info_desc <>", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescGreaterThan(String value) {
            addCriterion("job_info_desc >", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescGreaterThanOrEqualTo(String value) {
            addCriterion("job_info_desc >=", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescLessThan(String value) {
            addCriterion("job_info_desc <", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescLessThanOrEqualTo(String value) {
            addCriterion("job_info_desc <=", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescLike(String value) {
            addCriterion("job_info_desc like", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescNotLike(String value) {
            addCriterion("job_info_desc not like", value, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescIn(List<String> values) {
            addCriterion("job_info_desc in", values, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescNotIn(List<String> values) {
            addCriterion("job_info_desc not in", values, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescBetween(String value1, String value2) {
            addCriterion("job_info_desc between", value1, value2, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobInfoDescNotBetween(String value1, String value2) {
            addCriterion("job_info_desc not between", value1, value2, "jobInfoDesc");
            return (Criteria) this;
        }

        public Criteria andJobCompanyIsNull() {
            addCriterion("job_company is null");
            return (Criteria) this;
        }

        public Criteria andJobCompanyIsNotNull() {
            addCriterion("job_company is not null");
            return (Criteria) this;
        }

        public Criteria andJobCompanyEqualTo(String value) {
            addCriterion("job_company =", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyNotEqualTo(String value) {
            addCriterion("job_company <>", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyGreaterThan(String value) {
            addCriterion("job_company >", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("job_company >=", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyLessThan(String value) {
            addCriterion("job_company <", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyLessThanOrEqualTo(String value) {
            addCriterion("job_company <=", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyLike(String value) {
            addCriterion("job_company like", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyNotLike(String value) {
            addCriterion("job_company not like", value, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyIn(List<String> values) {
            addCriterion("job_company in", values, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyNotIn(List<String> values) {
            addCriterion("job_company not in", values, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyBetween(String value1, String value2) {
            addCriterion("job_company between", value1, value2, "jobCompany");
            return (Criteria) this;
        }

        public Criteria andJobCompanyNotBetween(String value1, String value2) {
            addCriterion("job_company not between", value1, value2, "jobCompany");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 13 10:37:18 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     *
     * @mbg.generated Sun Mar 13 10:37:18 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}